name: EndCrystal
version: '${project.version}'
main: io.github.javierscode.endcrystal.EndCrystal
api-version: 1.15
authors: [ JaviersCode,DiffuseHyperion ]
description: PVP made easy
commands:
  stats:
    description: Show your PVP stats!
    usage: /stats (kills/deaths/recentdeaths/recentkills) "player name"
  top:
    description: Shows the leaderboard of the server!
    usage: /top (kills/deaths)
